# Generated by Django 4.2.7 on 2026-07-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0002_alter_userprofile_options_userprofile_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
