# Generated by Django 5.2.16 on 2026-07-15 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0004_alter_userprofile_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangays', to='reeftrack_app.municipality')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'municipality')},
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.CharField(help_text='CPCe assessment identifier', max_length=100, unique=True)),
                ('assessment_date', models.DateField()),
                ('methodology', models.CharField(choices=[('photo_quadrat', 'Photo-Quadrat Survey'), ('line_transect', 'Line Transect'), ('point_intercept', 'Point Intercept'), ('other', 'Other')], default='photo_quadrat', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('condition', models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20, null=True)),
                ('overall_coral_cover', models.DecimalField(blank=True, decimal_places=4, help_text='Final Mean coral cover %', max_digits=7, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='reeftrack_app.barangay')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='reeftrack_app.municipality')),
            ],
            options={
                'ordering': ['-assessment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(help_text='e.g. ACROPORA BRANCHING (ACB)', max_length=200)),
                ('major_category', models.CharField(help_text='Family, e.g. ACROPORIDAE', max_length=200)),
                ('code', models.CharField(blank=True, help_text='Short code extracted from name', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Species',
                'ordering': ['major_category', 'sub_category'],
                'unique_together': {('sub_category', 'major_category')},
            },
        ),
        migrations.CreateModel(
            name='Transect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transect_number', models.PositiveIntegerField()),
                ('shallow_start_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('shallow_start_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('shallow_end_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('shallow_end_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('deep_start_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('deep_start_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('deep_end_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('deep_end_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('shallow_avg_cover', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('deep_avg_cover', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transects', to='reeftrack_app.assessment')),
            ],
            options={
                'ordering': ['transect_number'],
                'unique_together': {('assessment', 'transect_number')},
            },
        ),
        migrations.CreateModel(
            name='TransectSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shallow_cover', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('deep_cover', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('mean_cover', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transect_data', to='reeftrack_app.species')),
                ('transect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_data', to='reeftrack_app.transect')),
            ],
            options={
                'ordering': ['species__major_category', 'species__sub_category'],
                'unique_together': {('transect', 'species')},
            },
        ),
    ]
