# Generated by Django 5.2.16 on 2026-07-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0005_municipality_barangay_assessment_species_transect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='excel_file',
            field=models.FileField(blank=True, help_text='CPCe Excel file', null=True, upload_to='assessments/excel/'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='thesis_pdf',
            field=models.FileField(blank=True, help_text='Assessment thesis PDF', null=True, upload_to='assessments/thesis/'),
        ),
        migrations.CreateModel(
            name='AssessmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assessments/images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reeftrack_app.assessment')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
