# Generated by Django 5.2.16 on 2026-07-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0007_simplify_transect_and_transectspecies_remove_assessment_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transectspecies',
            options={'ordering': ['depth', 'species__major_category', 'species__sub_category']},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='thesis_pdf',
            field=models.FileField(blank=True, null=True, upload_to='assessments/thesis/'),
        ),
    ]
