# Generated by Django 5.2.16 on 2026-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0008_alter_transectspecies_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='source',
            field=models.CharField(choices=[('manual', 'Manually Added'), ('assessment', 'Created from Assessment')], default='manual', max_length=20),
        ),
    ]
