# Generated by Django 5.2.16 on 2026-07-16 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0009_species_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the assessment', null=True),
        ),
    ]
