# Generated by Django 5.2.16 on 2026-07-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0012_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transect',
            name='deep_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transect',
            name='deep_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transect',
            name='shallow_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transect',
            name='shallow_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
