# Generated by Django 5.2.16 on 2026-07-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0013_alter_transect_deep_lat_alter_transect_deep_lng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='assessment',
            name='methodology',
            field=models.CharField(default='photo_quadrat', max_length=100),
        ),
    ]
