# Generated by Django 5.2.16 on 2026-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0014_custommethodology_alter_assessment_methodology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transect',
            name='deep_lat',
        ),
        migrations.RemoveField(
            model_name='transect',
            name='deep_lng',
        ),
        migrations.RemoveField(
            model_name='transect',
            name='shallow_lat',
        ),
        migrations.RemoveField(
            model_name='transect',
            name='shallow_lng',
        ),
        migrations.AddField(
            model_name='transect',
            name='deep_end_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transect',
            name='deep_end_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transect',
            name='deep_start_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transect',
            name='deep_start_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transect',
            name='shallow_end_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transect',
            name='shallow_end_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transect',
            name='shallow_start_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transect',
            name='shallow_start_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
