# Generated by Django 5.2.16 on 2026-07-17 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0015_remove_transect_deep_lat_remove_transect_deep_lng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayTransect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transect_number', models.PositiveIntegerField()),
                ('shallow_start_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('shallow_start_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('shallow_end_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('shallow_end_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('deep_start_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('deep_start_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('deep_end_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('deep_end_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manually Added'), ('assessment', 'Created from Assessment')], default='manual', max_length=20)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_transect_coords', to='reeftrack_app.assessment')),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangay_transects', to='reeftrack_app.barangay')),
            ],
            options={
                'ordering': ['barangay', 'transect_number'],
                'unique_together': {('barangay', 'transect_number')},
            },
        ),
    ]
