# Generated by Django 5.2.16 on 2026-07-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0016_barangaytransect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangaytransect',
            options={'ordering': ['barangay', 'pk']},
        ),
        migrations.AlterUniqueTogether(
            name='barangaytransect',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='barangaytransect',
            name='transect_number',
        ),
    ]
