# Generated by Django 5.2.16 on 2026-07-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0017_remove_transect_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the assessment was approved', null=True),
        ),
    ]
