# Generated by Django 5.2.16 on 2026-07-18 13:13

from django.db import migrations, models


def truncate_middle_initials(apps, schema_editor):
    UserProfile = apps.get_model('reeftrack_app', 'UserProfile')
    for profile in UserProfile.objects.exclude(middle_initial=''):
        if len(profile.middle_initial) > 1:
            profile.middle_initial = profile.middle_initial[0]
            profile.save(update_fields=['middle_initial'])
    Contributor = apps.get_model('reeftrack_app', 'Contributor')
    for c in Contributor.objects.exclude(middle_initial=''):
        if len(c.middle_initial) > 1:
            c.middle_initial = c.middle_initial[0]
            c.save(update_fields=['middle_initial'])


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0018_add_approved_at_to_assessment'),
    ]

    operations = [
        migrations.RunPython(truncate_middle_initials, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contributor',
            name='middle_initial',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='middle_initial',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
