# Generated by Django 5.2.16 on 2026-07-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0022_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangaytransect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
