# Generated by Django 5.2.16 on 2026-07-24 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0026_municipality_province_non_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Login Locked Out'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('account_created', 'Account Created'), ('account_approved', 'Account Approved'), ('account_rejected', 'Account Rejected'), ('account_deactivated', 'Account Deactivated'), ('assessment_approved', 'Assessment Approved'), ('assessment_rejected', 'Assessment Rejected'), ('assessment_deleted', 'Assessment Deleted'), ('user_role_changed', 'User Role Changed')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='reeftrack_a_event_e813a6_idx'), models.Index(fields=['user', '-created_at'], name='reeftrack_a_user_id_beb4ea_idx'), models.Index(fields=['ip_address', '-created_at'], name='reeftrack_a_ip_addr_82eafa_idx')],
            },
        ),
    ]
