# Generated by Django 5.2.16 on 2026-08-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0028_assessmentdraft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentDraft',
        ),
    ]
