# Generated by Django 5.2.16 on 2026-08-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0029_delete_assessmentdraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
