# Generated by Django 5.2.16 on 2026-08-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0030_alter_assessment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_completed',
            field=models.BooleanField(default=True, help_text='False for users who signed in with Google and still need to fill in their name details.'),
        ),
    ]
