# Generated by Django 5.2.16 on 2026-08-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0034_title_case_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='transect',
            name='deep_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Estimated Deep Depth (m)'),
        ),
        migrations.AddField(
            model_name='transect',
            name='shallow_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Estimated Shallow Depth (m)'),
        ),
    ]
