# Generated by Django 5.2.16 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0035_transect_deep_depth_transect_shallow_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='affiliation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Affiliation / Organization'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Position / Specialization'),
        ),
    ]