# Generated by Django 5.2.16 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0036_userprofile_affiliation_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('marine_biologist', 'Marine Biologist'), ('research_associate', 'Research Associate'), ('research_assistant', 'Research Assistant'), ('field_technician', 'Field Technician'), ('student_intern', 'Student / Intern'), ('professor_educator', 'Professor / Educator'), ('coastal_resource_manager', 'Coastal Resource Manager'), ('government_staff', 'Government Staff'), ('other', 'Other')], default='', max_length=200, verbose_name='Position / Specialization'),
        ),
    ]