# Generated by Django 5.2.16 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0037_alter_userprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='affiliation',
            field=models.CharField(choices=[('university_institution', 'University / Academic Institution'), ('research_institute', 'Research Institute'), ('government_agency', 'Government Agency'), ('lgu', 'Local Government Unit (LGU)'), ('ngo', 'Non-Government Organization (NGO)'), ('private_sector', 'Private Sector / Consultancy'), ('community_org', 'Community / Fisherfolk Organization'), ('independent', 'Independent / Volunteer'), ('other', 'Other')], max_length=200, verbose_name='Affiliation / Organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('marine_biologist', 'Marine Biologist'), ('research_associate', 'Research Associate'), ('research_assistant', 'Research Assistant'), ('field_technician', 'Field Technician'), ('student_intern', 'Student / Intern'), ('professor_educator', 'Professor / Educator'), ('coastal_resource_manager', 'Coastal Resource Manager'), ('government_staff', 'Government Staff'), ('other', 'Other')], max_length=200, verbose_name='Position / Specialization'),
        ),
    ]