# Generated by Django 5.2.16 on 2026-10-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeftrack_app', '0038_alter_userprofile_affiliation_position_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='boundary',
            field=models.JSONField(blank=True, help_text='GeoJSON geometry (Polygon / MultiPolygon / Point)', null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='boundary',
            field=models.JSONField(blank=True, help_text='GeoJSON geometry (Polygon / MultiPolygon / Point)', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='boundary',
            field=models.JSONField(blank=True, help_text='GeoJSON geometry (Polygon / MultiPolygon / Point)', null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
